server:
  port: 8081
  servlet:
    context-path: /yumyum
spring:
  datasource:
    #    AWS setting:
        driver-class-name: org.mariadb.jdbc.Driver
        url: jdbc:mariadb://localhost:3306/ssafydb?characterEncoding=UTF-8&serverTimezone=Asia/Seoul
        username: yumyum
        password: yumyumb206
    #    local setting:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/ssafydb?serverTimezone=UTC&characterEncoding=UTF-8&serverTimezone=Asia/Seoul
#    username: ssafy4
#    password: ssafy4
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 256MB
      max-request-size: 256MB

  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: false
    show-sql: true
    hibernate:
      format_sql: true
      ddl-auto: update
  messages:
    basename: i18n/exception
    encoding: UTF-8

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE